# Report on the metrics Corp IT have requested

install_dir: C:\deployment\

- name: copy script to server
  win_copy:
    src: files/collect-inventory.ps1
    dest: "{{ install_dir }}//collect-inventory.ps1"

- name: Run script to collect an inventory for Corp IT
  win_shell: "{{ install_dir }}//collect-inventory.ps1"
  become: true
  become_method: runas


