---
# Install Workspace App via Chocolatey

- name: Install Workspace App via Chocolatey
  ansible.windows.win_powershell:
    script: |
      $Script = "app-choco-workspace-app.ps1"
      
      $BuildSource = "C:\deployment"
      $ScriptSource = "$BuildSource\scripts"
      $CustomSource = "$BuildSource\custom"

      & "$ScriptSource\$Script"

- name: Reboot after Workspace App Install
  ansible.windows.win_reboot: