---
# Install Base Image Script Framework via Chocolatey
- name: Install Base Image Script Framework via Chocolatey
  ansible.windows.win_powershell:
    script: |
      $Script = "app-choco-bisf.ps1"
      
      $BuildSource = "C:\deployment"
      $ScriptSource = "$BuildSource\scripts"
      $CustomSource = "$BuildSource\custom"

      & "$ScriptSource\$Script"
