---
# Run Import Start Layout
- name: Run Import Start Layout
  ansible.windows.win_powershell:
    script: |
      $Layout = "CustomLayout-Basic-Office-x64.xml"
      $BuildSource = "C:\deployment"
      $CustomSource = "$BuildSource\custom"
      $LayoutPath = "$CustomSource\$Layout"

      Import-StartLayout -LayoutPath $LayoutPath -MountPath 'c:\' -Verbose