---
# Install PowerBI via Nevergreen
- name: Install PowerBI via Nevergreen
  ansible.windows.win_powershell:
    script: |
      $Script = "app-nevergeen-powerbi.ps1"
      
      $BuildSource = "C:\deployment"
      $ScriptSource = "$BuildSource\scripts"
      $CustomSource = "$BuildSource\custom"

      & "$ScriptSource\$Script"