---
# Install 7 zip via Chocolatey
- name: Install 7 zip via Chocolatey
  ansible.windows.win_powershell:
    script: |
      $Script = "app-choco-7zip.ps1"
      
      $BuildSource = "C:\deployment"
      $ScriptSource = "$BuildSource\scripts"
      $CustomSource = "$BuildSource\custom"

      & "$ScriptSource\$Script"