---
# Set Windows sysprep
- name: create scheduled task to sysprep
  community.windows.win_scheduled_task:
    name: sysprep-shutdown
    username: SYSTEM
    disallow_start_if_on_batteries: false
    stop_if_going_on_batteries: false
    actions:
      - path: C:\windows\system32\sysprep\sysprep.exe
        arguments: /generalize /oobe /quit /quiet

- name: run sysprep-shutdown scheduled task
  ansible.windows.win_shell: schtasks.exe /Run /TN "sysprep-shutdown"
  failed_when: false