---
- name: Install .Net 3.5
  ansible.windows.win_optional_feature:
    name: NetFx3
    source: "\\\\ws-mdt\\mdtloginvsi$\\Operating Systems\\{{ winos_path }}\\sources\\sxs"
    state: present
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=net_credentials_only
  register: win_feature

- name: Reboot if required
  ansible.windows.win_reboot:
  when: win_feature.reboot_required