#
# Module manifest for module 'PLAY'
#
# Generated by: h.hofs
#
# Generated on: 21/11/2020
#

@{
    RootModule           = 'VSI.Target.Azure.psm1'
    # Version number of this module.
    ModuleVersion        = '0.0.0.1'

    # Supported PSEditions
    CompatiblePSEditions = @("Desktop","Core")

    # ID used to uniquely identify this module
    GUID                 = '2dc666f9-6e48-47ea-932a-4705517411b4'

    # Author of this module
    Author               = 'h.hofs@loginvsi.com', 'h.koelewijn@loginvsi.com'

    # Company or vendor of this module
    CompanyName          = 'LoginVSI'

    # Copyright statement for this module
    Copyright            = '(c) LoginVSI. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'Module for Automating Azure actions'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    CmdLetsToExport      = @('*-VSIAZ*')
    FunctionsToExport    = @('*-VSIAZ*')
    VariablesToExport    = @("VSIAZ_*")

}
