---
- hosts: all
  vars_files:
      - ./azure_vars/vars_azure_common.yml
  vars:
    ansible_user: "NtnxAzureAdmin"
    ansible_password: "this_is@VeryNaughtyPW1234$$"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
  tasks:
  - name: Test connection
    win_ping:

  # Copy deployment scripts and configuration files
  - name: Copy deployment scripts and configuration files
    win_copy:
      src: /workspaces/solutions-euc/engineering/lab/image-content/
      dest: C:/deployment/
      force: yes
    become: yes
    become_method: runas
    become_flags: logon_type=new_credentials logon_flags=netcredentials_only

  - name: Tattoo Image
    ansible.windows.win_powershell:
      script: |
        $Script = "cust-image-tattoo-azure.ps1"
        
        $BuildSource = "C:\deployment"
        $ScriptSource = "$BuildSource\scripts"

        & "$ScriptSource\$Script"