---
- name: Install Windows Desktop Operating System with Office 2021 x64 - Login Enterprise - Omnissa
  hosts: all
  roles:
  - run_ms_deployment_scripts
  - install_ms_net_framework_3.5
  - install_ms_visual_c_2013u5
  - install_adobe_reader_dc
  - install_ms_office_2021_x64
  - install_ms_edge_122
  - run_ms_file_types
  - run_optimize
  - run_image_tattoo
  - run_software_inventory_corp_it
  - win_disable_win_updates
  - run_cust_sysprep

  tasks:
   - name: Kill Defender Scheduled Tasks
     ansible.windows.win_powershell:
      script: |
        Get-ScheduledTask -TaskPath '\Microsoft\Windows\Windows Defender\' | Disable-ScheduledTask

   - name: Kill Windows LSA
     ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
      name: RunAsPPL
      data: 00000000
      type: dword
     when:
        - ansible_distribution == 'Windows'
        - ansible_distribution_version == '11'