---
- name: Install Windows 10/11 Gold with Office 2021 x64 - LoginVSI - Horizon
  hosts: all
  roles:
  - run_ms_deployment_scripts
  - install_ms_net_framework_3.5
  - install_ms_visual_c_2013u5
  - install_vmware_horizon_agent_8.12_2312
  - install_adobe_reader_dc
  - install_ms_office_2021_x64
  - install_ms_edge_122
  - run_ms_file_types
  - run_cust_imageoptimize_citrix
  - run_image_tattoo
  - win_disable_win_updates