---
- name: Install Windows 10 Gold with heavy app set
  hosts: all
  roles:
  - run_ms_deployment_scripts
  - install_ms_net_framework_3.5
  - install_base_chocolatey
  - install_base_evergreen
  - install_base_nevergreen
  - install_latest_ms_vcredists
  - install_citrix_vda_client_2203_1
  - install_latest_7zip
  - install_latest_vlc
  - install_latest_ms_powerbi
  - install_latest_ms_365apps
  - install_latest_ms_teams
  - install_latest_ms_fslogix
  - install_latest_bisf
  - install_latest_adobe_reader
  - install_latest_mozilla_firefox
  - install_latest_greenshot
  - install_latest_notepadplusplus
  - install_latest_ms_onedrive
  - install_latest_google_chrome
