---
# Install VMware Tools

- name: Create install directory for ansible operations
  win_file: 
    path: "{{ install_dir }}"
    state: directory

- name: copy script to server
  win_copy:
    src: files/get-VMwareTools.ps1
    dest: "{{ install_dir }}//get-VMwareTools.ps1"

- name: Run script to install the latest VMware Tools 
  win_shell: "{{ install_dir }}//get-VMwareTools.ps1"
  become: true
  become_method: runas