---
- name: Omnissa Post Deployment Optimizations - Manual Pool
  hosts: all
  vars_files:
    - ./omnissa_vars/all.yml
  roles:
    - install_omnissa_horizon_agent_8.12_2312_manual
    - run_optimize

  tasks:
   - name: Kill Defender Scheduled Tasks
     ansible.windows.win_powershell:
      script: |
        Get-ScheduledTask -TaskPath '\Microsoft\Windows\Windows Defender\' | Disable-ScheduledTask

   - name: Kill Windows LSA
     ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
      name: RunAsPPL
      data: 00000000
      type: dword
     when:
        - ansible_distribution == 'Windows'
        - ansible_distribution_version == '11'