---
# Install Greenshot via Chocolatey
- name: Install Greenshot via Chocolatey
  ansible.windows.win_powershell:
    script: |
      $Script = "app-choco-greenshot.ps1"
      
      $BuildSource = "C:\deployment"
      $ScriptSource = "$BuildSource\scripts"
      $CustomSource = "$BuildSource\custom"

      & "$ScriptSource\$Script"