---
ansible_user: administrator
ansible_domain_user: wsperf\administrator
ansible_password: "nutanix/4u"
ansible_become_user: wsperf\administrator
ansible_become_pass: "nutanix/4u"
sourcefiles_path: \\ws-files.wsperf.nutanix.com\Automation
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_port: 5986
citrix_delivery_controllers: WS-CDC1.wsperf.nutanix.com,WS-CDC2.wsperf.nutanix.com
grid_license_server: contmcdc001
wem_infra_server: ws-cdc1.wsperf.nutanix.com