- name: Schedule Workload start in the future.
  hosts: all
  gather_facts: true
  tasks:
  - name: Schedule start of workload start
    # Take the current time on the machine +60 seconds for when to start the workload
    win_command: "powershell.exe -ExecutionPolicy ByPass -File registerTask.ps1 -unixTime {{ ansible_date_time.epoch|int + 60 }}"
    args:
      chdir: 'C:\scripts'

