---
# Install Google Chrome via Chocolatey
- name: Install Google Chrome via Chocolatey
  ansible.windows.win_powershell:
    script: |
      $Script = "app-choco-google-chrome.ps1"
      
      $BuildSource = "C:\deployment"
      $ScriptSource = "$BuildSource\scripts"
      $CustomSource = "$BuildSource\custom"

      & "$ScriptSource\$Script"