#
# Copyright (c) 2023 Nutanix Inc. All rights reserved.
#
# Author: Errol Fouquet (errol@nutanix.com)
#

---

- name: Disable ADS

  hosts: cvms

  tasks:
    - name: disable ADS
      run_once: True
      shell: "source /etc/profile; acli ads.update enable=false"
