#
# Copyright (c) 2023 Nutanix Inc. All rights reserved.
#
# Author: Errol Fouquet (errol@nutanix.com)
#

---

- name: Enable ADS

  hosts: cvms

  tasks:
    - name: enable ADS
      run_once: True
      shell: "source /etc/profile; acli ads.update enable=true"
