---
# Install Adobe Reader via Chocolatey
- name: Install Adobe Reader via Chocolatey
  ansible.windows.win_powershell:
    script: |
      $Script = "app-choco-adobe-reader.ps1"
      
      $BuildSource = "C:\deployment"
      $ScriptSource = "$BuildSource\scripts"
      $CustomSource = "$BuildSource\custom"

      & "$ScriptSource\$Script"