---
# Install Login Enterprise Launcher
- name: Create Install Folder
  win_file:
    path: C:\\Install\\LE
    state: directory

- name: copy file from UNC path
  win_copy:
    src: "{{ sourcefiles_path }}\\Apps\\LoginVSI\\Enterprise\\Launcher\\{{ LE.version }}\\"
    dest: 'C:\Install\LE\'
    remote_src: true
    force: yes
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only

- name: Install Login Enterprise Launcher
  win_package:
    path: "C:\\Install\\LE\\Setup.msi"
    state: present
    creates_path: "C:\\Program Files\\Login VSI\\Login Enterprise Launcher\\LoginEnterprise.Launcher.UI.exe"
    creates_version: "{{ LE.version }}.0"
    arguments: 'serverurl={{ LE.url }} secret={{ LE.secret }}'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=net_credentials_only