---
# Install Google Chrome

- name: Delete default Install Key
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\EdgeUpdate
    name: InstallDefault
    state: absent

- name: Set Edge Updates
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\EdgeUpdate
    name: Update{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}
    data: 00000000
    type: dword

- name: Set Edge Rollback Allow
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\EdgeUpdate
    name: RollbackToTargetVersion{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}
    data: 00000001
    type: dword

- name: Set Edge Rollback Version to 122.0.2365.120
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\EdgeUpdate
    name: TargetVersionPrefix{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}
    data: 122.0.2365.120
    type: string

- name: Install Microsoft Edge 122.0.2365.120
  win_package:
    path: "{{ sourcefiles_path }}\\Apps\\Microsoft\\Edge\\122\\MicrosoftEdgeEnterpriseX64.msi"
    state: present
    arguments: >-
      ALLOWDOWNGRADE=1
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=net_credentials_only

- name: Set Edge Update service startup mode to disabled and ensure it is stopped
  ansible.windows.win_service:
    name: edgeupdate
    start_mode: disabled
    state: stopped

- name: Set Edge Update service m startup mode to disabled and ensure it is stopped
  ansible.windows.win_service:
    name: edgeupdatem
    start_mode: disabled
    state: stopped

- name: Disable Edge Schedule Tasks
  ansible.windows.win_powershell:
    script: |
      Disable-ScheduledTask -TaskName MicrosoftEdgeUpdateTaskMachineCore
      Disable-ScheduledTask -TaskName MicrosoftEdgeUpdateTaskMachineUA     