---
# Install Microsoft OneDrive via Chocolatey
- name: Install Microsoft OneDrive via Chocolatey
  ansible.windows.win_powershell:
    script: |
      $Script = "app-choco-ms-onedrive.ps1"
      
      $BuildSource = "C:\deployment"
      $ScriptSource = "$BuildSource\scripts"
      $CustomSource = "$BuildSource\custom"

      & "$ScriptSource\$Script"