---
install_dir: c:\ansible_install
cvad_source_path: '\\10.57.64.39\MDTLoginVSI$\Applications\Citrix_Virtual_Apps_and_Desktops_7_1912_6000'
nutanix_plugin_source_path: '\\10.57.64.39\MDTLoginVSI$\Applications\Nutanix'
nutanix_plugin_director_install: 'NutanixAHV_Citrix_Director_Plugin_Installer_1.1.3.0.msi'

sf_host_base_url: http://cvad1912.wsperf.nutanix.com
sf_gateway_url: https://cvad1912.wsperf.nutanix.com

build_version: 1912_LTSR # Build Version for Policy Import
build_number: "1912_6000"

#pvs_source_path: '\\10.57.64.39\MDTLoginVSI$\Applications\Citrix_Provisioning_2212'

#pvs_database_server: 10.57.64.115
pvs_database_instance: SQLEXPRESS
pvs_database_name: CTX_Provisioning_DB
pvs_farm_name: NutanixEUC
pvs_site_name: NutanixEUC
pvs_collection_name: Default
pvs_store: DefaultStore
pvs_store_path: C:\PVS_Store
pvs_admin_group: "wsperf.nutanix.com/users/Domain Admins"
#pvs_license_server: 10.57.64.115
pvs_username: wsperf\sa_pvs_lab
pvs_password: nutanix/4u