---
# Install Notepad ++ via Chocolatey
- name: Install Notepad ++ via Chocolatey
  ansible.windows.win_powershell:
    script: |
      $Script = "app-choco-notepadplusplus.ps1"
      
      $BuildSource = "C:\deployment"
      $ScriptSource = "$BuildSource\scripts"
      $CustomSource = "$BuildSource\custom"

      & "$ScriptSource\$Script"