---
- name: Reboot before Optimizations
  ansible.windows.win_reboot:

- name: Pause for 2 minutes
  ansible.builtin.pause:
    minutes: 2

# Run Citrix Optimizer
- name: Run Citrix Optimizer
  ansible.windows.win_powershell:
    script: |
      $Script = "cust-imageoptimize-citrix.ps1"
      
      $BuildSource = "C:\deployment"
      $ScriptSource = "$BuildSource\scripts"
      $CustomSource = "$BuildSource\custom"

      & "$ScriptSource\$Script"

- name: Reboot after Optimizations
  ansible.windows.win_reboot: