---
# Install Microsoft 365 Apps via Evergreen
- name: Install Microsoft 365 Apps via Evergreen
  ansible.windows.win_powershell:
    script: |
      $Script = "app-evergreen-ms-365apps.ps1"
      
      $BuildSource = "C:\deployment"
      $ScriptSource = "$BuildSource\scripts"
      $CustomSource = "$BuildSource\custom"

      & "$ScriptSource\$Script"