#
# Module manifest for module 'PLAY'
#
# Generated by: h.hofs
#
# Generated on: 21/11/2020
#

@{
    RootModule           = 'VSI.Target.CitrixVAD.psm1'
    # Version number of this module.
    ModuleVersion        = '0.0.0.1'

    # Supported PSEditions
    CompatiblePSEditions = @("Desktop")

    # ID used to uniquely identify this module
    GUID                 = '7bf28a7d-6f2f-44da-afba-5682f164de06'

    # Author of this module
    Author               = 'h.hofs@loginvsi.com', 'h.koelewijn@loginvsi.com'

    # Company or vendor of this module
    CompanyName          = 'LoginVSI'

    # Copyright statement for this module
    Copyright            = '(c) LoginVSI. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'Module for Automationg Horizon View actions'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    CmdLetsToExport      = @('*-VSICTX*')
    FunctionsToExport    = @('*-VSICTX*')
    VariablesToExport    = @("VSICTX_*")

}
