---
# Install Omnissa Horizon Agent for manual pool
- name: Create Log Folder
  win_file:
    path: C:\\Logs
    state: directory

- name: Install Horizon Agent client
  win_package:
    path: "{{ sourcefiles_path }}\\Apps\\Omnissa\\Horizon 8.12 - 2312\\VMware-Horizon-Agent-x86_64-2312-8.12.0-23142606.exe"
    arguments: /s /v"/qn REBOOT=ReallySuppress VDM_VC_MANAGED_AGENT=0 VDM_SERVER_NAME={{ horizon_connection_server }} VDM_SERVER_USERNAME={{ horizon_user }} VDM_SERVER_PASSWORD={{ horizon_password }} RDP_CHOICE=1 ADDLOCAL=Core,BlastUDP,NGVC,VmwVaudio,USB,RTAV,PerfTracker,HelpDesk"
    state: present
    expected_return_code: [0, 3010]
    product_id: '{9C724D00-B477-4065-B690-B424C1F2CB9E}'
    log_path: C:\\Logs\\HorizonAgent.log
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=net_credentials_only
  register: HorizonAgent_install

- name: Reboot to complete VMware Horizon Agent install
  ansible.windows.win_reboot:
  when: HorizonAgent_install.changed