---
# Install Office 365
- name: Create Log Folder
  win_file:
    path: C:\Logs
    state: directory

- name: Install Office 365
  win_package:
    path: "{{ sourcefiles_path }}\\Apps\\Microsoft\\Office\\365 - x64\\Setup.exe"
    arguments: /configure "{{ sourcefiles_path }}\\Apps\\Microsoft\\Office\\365 - x64\\customization.xml"
    state: present
    creates_path: C:\Program Files\Microsoft Office
    product_id: '{90160000-00DD-0000-1000-0000000FF1CE}'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=net_credentials_only
  register: office365_install

- name: Change Click to Run registry key
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Office\ClickToRun\Configuration
    name: WatcherInterval
    data: 360000000

- name: Disable Activation registry key
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Office\16.0\Common\Licensing
    name: DisableActivationUI
    data: 1
    type: dword