---
# Install VC Redists via Get-VCRedist PS Module
- name: Install VC Redists via Get-VCRedist PS Module
  ansible.windows.win_powershell:
    script: |
      $Script = "app-ms-vcredists.ps1"
      
      $BuildSource = "C:\deployment"
      $ScriptSource = "$BuildSource\scripts"
      $CustomSource = "$BuildSource\custom"

      & "$ScriptSource\$Script"