---
# Run Cleanup Image Temp Files
- name: Run Cleanup Image Temp Files
  ansible.windows.win_powershell:
    script: |
      $PathToClean = "C:\Apps\Temp"

      if (Test-Path -Path $PathToClean) {
        Remove-Item -path $PathToClean -force -Recurse
      }