---
vm_name: "kindo-test"
vm_sku: "Standard_DS1_v2"
license_type: "Windows_Client"
disk_sku: "StandardSSD_LRS"
disk_size: 127
admin_username: "NtnxAzureAdmin"
admin_password: "this_is@VeryNaughtyPW1234$$"
offer: "WindowsServer"
publisher: "MicrosoftWindowsServer"
sku: "2022-datacenter-g2"
accelerated_networking: true
winrm_timeout: 30 #600
winrm_port: 5986